services:
  backend:
    build: ./Backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"

  frontend:
    build: ./Frontend
    container_name: streamlit_frontend
    environment:
      API_BASE_URL: http://backend:8000
    ports:
      - "8501:8501"
    depends_on:
      - backend
